"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['sum_csv_files.py']
DATA_FILES = []
OPTIONS = {'plist': {"CFBundleVersion": "1.0.0",
                     "CFBundleShortVersionString": "1.0.0"
                     }
          }              

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
